[743863765975564368]
Healbrand = false
Alacrigade = false
DPS1 = false
DPS2 = false
DPS3 = false

[743864798667866202]
Healbrand = false
Alacrigade = false
BS = false
DPS2 = false
DPS3 = false

[743868251313799349]
Healbrand = false
Alacrigade = false
DPS1 = false
DPS2 = false
DPS3 = false

[743868547146711220]
Healbrand = false
Alacrigade = false
BS = false
DPS1 = false
DPS2 = false

[743868647675658290]
Healbrand = false
Alacrigade = false
DPS1 = "Deadeye"
DPS2 = "Berserker"
DPS3 = "Reaper"

[743876511320244267]
Healbrand = false
Alacrigade = "Renegade"
DPS1 = "Herald"
DPS2 = "Renegade"
DPS3 = false
