[Elementalist]
    [Elementalist.Tempest]
        [Elementalist.Tempest.Power]
            [Elementalist.Tempest.Power.Primary]
            name = 'Plate of Coq Au Vin with Salsa'
            link = 'https://wiki.guildwars2.com/wiki/Plate_of_Coq_Au_Vin_with_Salsa'
            [Elementalist.Tempest.Power.Secondary]
            name = 'Plate of Peppercorn-Spiced Coq Au Vin'
            link = 'https://wiki.guildwars2.com/wiki/Plate_of_Peppercorn-Spiced_Coq_Au_Vin'
        [Elementalist.Tempest.Condition]
            [Elementalist.Tempest.Condition.Primary]
            name = 'Salsa-Topped Veggie Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Salsa-Topped_Veggie_Flatbread'
            [Elementalist.Tempest.Condition.Secondary]
            name = 'Peppercorn and Veggie Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn_and_Veggie_Flatbread'
        [Elementalist.Tempest.Heal]
            [Elementalist.Tempest.Heal.Primary]
            name = 'Bowl of Fruit Salad with Mint Garnish'
            link = 'https://wiki.guildwars2.com/wiki/Bowl_of_Fruit_Salad_with_Mint_Garnish'
    [Elementalist.Weaver]
        [Elementalist.Weaver.Power]
            [Elementalist.Weaver.Power.Primary]
            name = 'Cilantro Lime Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
            [Elementalist.Weaver.Power.Secondary]
            name = 'Peppercorn-Crusted Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'
        [Elementalist.Weaver.Condition]
            [Elementalist.Weaver.Condition.Primary]
            name = 'Salsa-Topped Veggie Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Salsa-Topped_Veggie_Flatbread'
            [Elementalist.Weaver.Condition.Secondary]
            name = 'Peppercorn and Veggie Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn_and_Veggie_Flatbread'
[Mesmer]
    [Mesmer.Chronomancer]
        [Mesmer.Chronomancer.Power]
            [Mesmer.Chronomancer.Power.Boon]
                [Mesmer.Chronomancer.Power.Boon.Primary]
                name = 'Cilantro Lime Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
                [Mesmer.Chronomancer.Power.Boon.Secondary]
                name = 'Peppercorn-Crusted Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'
                [Mesmer.Chronomancer.Power.Boon.Tertiary]
                name = 'Beef Carpaccio with Salsa Garnish'
                link = 'https://wiki.guildwars2.com/wiki/Plate_of_Beef_Carpaccio_with_Salsa_Garnish'
                [Mesmer.Chronomancer.Power.Boon.Quartiary]
                name = 'Peppercorn-Spiced Beef Carpaccio'
                link = 'https://wiki.guildwars2.com/wiki/Plate_of_Peppercorn-Spiced_Beef_Carpaccio'
            [Mesmer.Chronomancer.Power.DPS]
                [Mesmer.Chronomancer.Power.DPS.Primary]
                name = 'Cilantro Lime Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
                [Mesmer.Chronomancer.Power.DPS.Secondary]
                name = 'Peppercorn-Crusted Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'
        [Mesmer.Chronmancer.Condition]
            [Mesmer.Chronomancer.Condition.Tank]
                [Mesmer.Chronomancer.Condition.Tank.Primary]
                name = 'Peppercorn-Spiced Eggs Benedict'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Spiced_Eggs_Benedict'
            [Mesmer.Chronomancer.Condition.DPS]
                [Mesmer.Chronomancer.Condition.DPS.Primary]
                name = 'Cilantro and Cured Meat Flatbread'
                link = 'https://wiki.guildwars2.com/wiki/Cilantro_and_Cured_Meat_Flatbread'
                [Mesmer.Chronomancer.Condition.DPS.Secondary]
                name = 'Peppered Cured Meat Flatbread'
                link = 'https://wiki.guildwars2.com/wiki/Peppered_Cured_Meat_Flatbread'
    [Mesmer.Mirage]
        [Mesmer.Mirage.Condition]
            [Mesmer.Mirage.Condition.Primary]
            name = 'Salsa-Topped Veggie Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Salsa-Topped_Veggie_Flatbread'
            [Mesmer.Mirage.Condition.Secondary]
            name = 'Peppercorn and Veggie Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn_and_Veggie_Flatbread'
[Necromancer]
    [Necromancer.Reaper]
        [Necromancer.Reaper.Power]
            [Necromancer.Reaper.Power.Primary]
            name = 'Cilantro Lime Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
            [Necromancer.Reaper.Power.Secondary]
            name = 'Peppercorn-Crusted Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'
    [Necromancer.Scourge]
        [Necromancer.Scourge.Condition]
            [Necromancer.Scourge.Condition.Primary]
            name = 'Cilantro and Cured Meat Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_and_Cured_Meat_Flatbread'
            [Necromancer.Scourge.Condition.Secondary]
            name = 'Peppered Cured Meat Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Peppered_Cured_Meat_Flatbread'
        [Necromancer.Scourge.Heal]
            [Necromancer.Scourge.Heal.Primary]
            name = 'Bowl of Fruit Salad with Mint Garnish'
            link = 'https://wiki.guildwars2.com/wiki/Bowl_of_Fruit_Salad_with_Mint_Garnish'
[Engineer]
    [Engineer.Engineer]
        [Engineer.Engineer.Condition]
            [Engineer.Engineer.Condition.Primary]
            name = 'Cilantro and Cured Meat Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_and_Cured_Meat_Flatbread'
            [Engineer.Engineer.Condition.Secondary]
            name = 'Peppered Cured Meat Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Peppered_Cured_Meat_Flatbread'
    [Engineer.Holosmith]
        [Engineer.Holosmith.Power]
            [Engineer.Holosmith.Power.Primary]
            name = 'Cilantro Lime Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
            [Engineer.Holosmith.Power.Secondary]
            name = 'Peppercorn-Crusted Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'
    [Engineer.Scrapper]
        [Engineer.Scrapper.Heal]
            [Engineer.Scrapper.Heal.Primary]
            name = 'Bowl of Fruit Salad with Mint Garnish'
            link = 'https://wiki.guildwars2.com/wiki/Bowl_of_Fruit_Salad_with_Mint_Garnish'     
[Ranger]
    [Ranger.Druid]
        [Ranger.Druid.Heal]
            [Ranger.Druid.Heal.Primary]
            name = 'Bowl of Fruit Salad with Mint Garnish'
            link = 'https://wiki.guildwars2.com/wiki/Bowl_of_Fruit_Salad_with_Mint_Garnish'
        [Ranger.Druid.Condition]
            [Ranger.Druid.Condition.Primary]
            name = 'Salsa-Topped Veggie Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Salsa-Topped_Veggie_Flatbread'
            [Ranger.Druid.Condition.Secondary]
            name = 'Peppercorn and Veggie Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn_and_Veggie_Flatbread'
    [Ranger.Soulbeast]
        [Ranger.Soulbeast.Power]
            [Ranger.Soulbeast.Power.Primary]
            name = 'Cilantro Lime Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
            [Ranger.Soulbeast.Power.Secondary]
            name = 'Peppercorn-Crusted Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'
        [Ranger.Soulbeast.Condition]
            [Ranger.Soulbeast.Condition.Primary]
            name = 'Cilantro and Cured Meat Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_and_Cured_Meat_Flatbread'
            [Ranger.Soulbeast.Condition.Secondary]
            name = 'Peppered Cured Meat Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Peppered_Cured_Meat_Flatbread'
        [Ranger.Soulbeast.Handkite]
            [Ranger.Soulbeast.Handkite.Primary]
            name = 'Spiced Fruit Salad'
            link = 'https://wiki.guildwars2.com/wiki/Bowl_of_Spiced_Fruit_Salad'
[Thief]
    [Thief.Thief]
        [Thief.Thief.Power]
            [Thief.Thief.Power.Boon]
                [Thief.Thief.Power.Boon.Primary]
                name = 'Cilantro Lime Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
                [Thief.Thief.Power.Boon.Secondary]
                name = 'Peppercorn-Crusted Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'
    [Thief.Daredevil]
        [Thief.Daredevil.Power]
            [Thief.Daredevil.Power.DPS]
                [Thief.Daredevil.Power.DPS.Primary]
                name = 'Cilantro Lime Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
                [Thief.Daredevil.Power.DPS.Secondary]
                name = 'Peppercorn-Crusted Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'
            [Thief.Daredevil.Power.Boon]
                [Thief.Daredevil.Power.Boon.Primary]
                name = 'Cilantro Lime Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
                [Thief.Daredevil.Power.Boon.Secondary]
                name = 'Peppercorn-Crusted Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'
     
    [Thief.Deadeye]
        [Thief.Deadeye.Power]
            [Thief.Deadeye.Power.Primary]
            name = 'Cilantro Lime Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
            [Thief.Deadeye.Power.Secondary]
            name = 'Peppercorn-Crusted Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'        
[Guardian]
    [Guardian.Guardian]
        [Guardian.Guardian.Power]
            [Guardian.Guardian.Power.Primary]
            name = 'Cilantro Lime Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
            [Guardian.Guardian.Power.Secondary]
            name = 'Peppercorn-Crusted Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'  
    [Guardian.Dragonhunter]
        [Guardian.Dragonhunter.Power]
            [Guardian.Dragonhunter.Power.Primary]
            name = 'Cilantro Lime Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
            [Guardian.Dragonhunter.Power.Secondary]
            name = 'Peppercorn-Crusted Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'  
    [Guardian.Firebrand]
        [Guardian.Firebrand.Heal]
            [Guardian.Firebrand.Heal.Primary]
            name = 'Bowl of Fruit Salad with Mint Garnish'
            link = 'https://wiki.guildwars2.com/wiki/Bowl_of_Fruit_Salad_with_Mint_Garnish'
        [Guardian.Firebrand.Condition]
            [Guardian.Firebrand.Condition.Boon]
                [Guardian.Firebrand.Condition.Boon.Primary]
                name = 'Bowl of Fire Meat Chili'
                link = 'https://wiki.guildwars2.com/wiki/Bowl_of_Fire_Meat_Chili'
            [Guardian.Firebrand.Condition.DPS]
                [Guardian.Firebrand.Condition.DPS.Primary]
                name = 'Cilantro and Cured Meat Flatbread'
                link = 'https://wiki.guildwars2.com/wiki/Cilantro_and_Cured_Meat_Flatbread'
                [Guardian.Firebrand.Condition.DPS.Secondary]
                name = 'Peppered Cured Meat Flatbread'
                link = 'https://wiki.guildwars2.com/wiki/Peppered_Cured_Meat_Flatbread'
[Revenant]
    [Revenant.Herald]
        [Revenant.Herald.Power]
            [Revenant.Herald.Power.Boon]
                [Revenant.Herald.Power.Boon.Primary]
                name = 'Cilantro Lime Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
                [Revenant.Herald.Power.Boon.Secondary]
                name = 'Peppercorn-Crusted Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'  
        [Revenant.Herald.Handkite]
            [Revenant.Herald.Handkite.Primary]
            name = 'Spiced Fruit Salad'
            link = 'https://wiki.guildwars2.com/wiki/Bowl_of_Spiced_Fruit_Salad'
    [Revenant.Renegade]
        [Revenant.Renegade.Condition]
            [Revenant.Renegade.Condition.Primary]
            name = 'Cilantro and Cured Meat Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_and_Cured_Meat_Flatbread'
            [Revenant.Renegade.Condition.Secondary]
            name = 'Peppered Cured Meat Flatbread'
            link = 'https://wiki.guildwars2.com/wiki/Peppered_Cured_Meat_Flatbread'
        [Revenant.Renegade.Power]
            [Revenant.Renegade.Power.Boon]
                [Revenant.Renegade.Power.Boon.Primary]
                name = 'Cilantro Lime Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
                [Revenant.Renegade.Power.Boon.Secondary]
                name = 'Peppercorn-Crusted Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak' 
        [Revenant.Renegade.Heal] 
            [Revenant.Renegade.Heal.Primary]
            name = 'Bowl of Fruit Salad with Mint Garnish'
            link = 'https://wiki.guildwars2.com/wiki/Bowl_of_Fruit_Salad_with_Mint_Garnish'
[Warrior]
    [Warrior.Berserker]
        [Warrior.Berserker.Power]
            [Warrior.Berserker.Power.Boon]
                [Warrior.Berserker.Power.Boon.Primary]
                name = 'Cilantro Lime Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
                [Warrior.Berserker.Power.Boon.Secondary]
                name = 'Peppercorn-Crusted Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'  
            [Warrior.Berserker.Power.DPS]
                [Warrior.Berserker.Power.DPS.Primary]
                name = 'Cilantro Lime Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
                [Warrior.Berserker.Power.DPS.Secondary]
                name = 'Peppercorn-Crusted Sous-Vide Steak'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'
        [Warrior.Berserker.Condition]
            [Warrior.Berserker.Condition.Boon]
                [Warrior.Berserker.Condition.Boon.Primary]
                name = 'Salsa-Topped Veggie Flatbread'
                link = 'https://wiki.guildwars2.com/wiki/Salsa-Topped_Veggie_Flatbread'
                [Warrior.Berserker.Condition.Boon.Secondary]
                name = 'Peppercorn and Veggie Flatbread'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn_and_Veggie_Flatbread'
            [Warrior.Berserker.Condition.DPS]
                [Warrior.Berserker.Condition.DPS.Primary]
                name = 'Salsa-Topped Veggie Flatbread'
                link = 'https://wiki.guildwars2.com/wiki/Salsa-Topped_Veggie_Flatbread'
                [Warrior.Berserker.Condition.DPS.Secondary]
                name = 'Peppercorn and Veggie Flatbread'
                link = 'https://wiki.guildwars2.com/wiki/Peppercorn_and_Veggie_Flatbread'
    [Warrior.Spellbreaker]
        [Warrior.Spellbreaker.Power]
            [Warrior.Spellbreaker.Power.Primary]
            name = 'Cilantro Lime Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Cilantro_Lime_Sous-Vide_Steak'
            [Warrior.Spellbreaker.Power.Secondary]
            name = 'Peppercorn-Crusted Sous-Vide Steak'
            link = 'https://wiki.guildwars2.com/wiki/Peppercorn-Crusted_Sous-Vide_Steak'

        